---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---

print("^1 RageUI - testing file is started. ^0")


local fuelMenu = RageUI.CreateMenu("", "FUEL", nil, nil, "shopui_title_gasstation", "shopui_title_gasstation")
local subMenu =  RageUI.CreateSubMenu(fuelMenu, "A TITLE", "A SUB TITLE")

fuelMenu:DisplayGlare(false)
fuelMenu.Closed = function()
    print('Closed Showcase Menu')
end
fuelMenu.EnableMouse = true
fuelMenu.onIndexChange = function(Index)
    print(Index)
end

--> This will show the glare on the submenu : 
subMenu:DisplayGlare(true)

--> This will show the page counter on the submenu :
subMenu:DisplayPageCounter(true)

local ParentData = {mom = 0, dad = 0}
local index = {
    checkbox = false,
    list = 2,
    heritage = 0.5,
    slider = 50,
    sliderprogress = 50,
    grid = {
        default = { x = 0.5, y = 0.5 },
        horizontal = { x = 0.5 },
        vertical = { y = 0.5 },
    },
    percentage = 0.5,
    color = {
        primary = { 1, 5 },
        secondary = { 1, 5 }
    },
}

local description = carname

Citizen.CreateThread(function()
    while (true) do
        Citizen.Wait(1.0)

        RageUI.IsVisible(fuelMenu, function()
            --
            local ped = GetPlayerPed(PlayerId())
local veh = GetLastDrivenVehicle(ped)
local model = GetEntityModel(veh)
local displaytext = GetDisplayNameFromVehicleModel(model)
local carname = GetLabelText(displaytext)
local plate = GetVehicleNumberPlateText(veh) or "pussy"
--
           

            RageUI.List('Fill Up', {
                { Name = "Quarter", Value = 17 },
                { Name = "Half", Value = 33 },
                { Name = "3/4", Value = 45 },
                { Name = "Full", Value = 65 },
            }, index.list, "Fuelling: ".. carname .." (".. plate ..")", {}, true, {
                onListChange = function(Index, Item)
                    index.list = Index;
                    Visual.Subtitle("onListChange", 100)
                end,
                onSelected = function(Index, Item)
                    Visual.Subtitle("onSelected", 100)
                end,
            })

           
        end, function()

          




          

            RageUI.ColourPanel("Couleur de paco secondaire", RageUI.PanelColour.HairCut, index.color.secondary[1], index.color.secondary[2], {
                onColorChange = function(MinimumIndex, CurrentIndex)
                    index.color.secondary[1] = MinimumIndex
                    index.color.secondary[2] = CurrentIndex
                end
            }, 6)
        end)

        --> SubMenu : 
        RageUI.IsVisible(subMenu, function()
            --> EXEMPLE ON HOW TO USE HERITAGE WINDOW : 
            RageUI.Window.Heritage(ParentData['mom'], ParentData['dad'])

            --> your logic here ... 
        end, function() end)
    end
end)


Keys.Register('E', 'E', 'Open RageUI Showcase menu default.', function()
    RageUI.Visible(fuelMenu, not RageUI.Visible(fuelMenu))
end)