---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---

print("^1 RageUI - testing file is started. ^0")

local armoryMenu = RageUI.CreateMenu("LSPD", "ARMORY")
local subMenu =  RageUI.CreateSubMenu(armoryMenu, "A TITLE", "A SUB TITLE")

armoryMenu:DisplayGlare(false)
armoryMenu.Closed = function()
    print('Closed Showcase Menu')
end
armoryMenu.EnableMouse = true
armoryMenu.onIndexChange = function(Index)
    print(Index)
end

--> This will show the glare on the submenu : 
subMenu:DisplayGlare(true)

--> This will show the page counter on the submenu :
subMenu:DisplayPageCounter(true)

local ParentData = {mom = 0, dad = 0}
local index = {
    checkbox = false,
    list = 2,
    heritage = 0.5,
    slider = 50,
    sliderprogress = 50,
    grid = {
        default = { x = 0.5, y = 0.5 },
        horizontal = { x = 0.5 },
        vertical = { y = 0.5 },
    },
    percentage = 0.5,
    color = {
        primary = { 1, 5 },
        secondary = { 1, 5 }
    },
}

local description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur"

Citizen.CreateThread(function()
    while (true) do
        Citizen.Wait(1.0)

        RageUI.IsVisible(armoryMenu, function()

            RageUI.Button('Standard Loadout', "yes", {}, true, {
                onHovered = function()
                    Visual.Subtitle("onHovered", 100)
                end,
                onSelected = function()
                    --Visual.Subtitle("onSelected", 100)
                    local ped = GetPlayerPed(PlayerId())
                    GiveWeaponToPed(ped, GetHashKey("WEAPON_FLASHLIGHT"), 1, false, false)
                    GiveWeaponToPed(ped, GetHashKey("WEAPON_NIGHTSTICK"), 1, false, false)
                    GiveWeaponToPed(ped, GetHashKey("WEAPON_STUNGUN"), 1, false, false)
                    GiveWeaponToPed(ped, GetHashKey("WEAPON_COMBATPISTOL"), 72, false, false)
                    SetPedComponentVariation(ped, 7, 6, 0, 0) -- neck
                    SetPedComponentVariation(ped, 8, 56, 0, 0) -- access
                end,
            });

            

            RageUI.List('Weapons', {
                { Name = "Flashlight", Value = "WEAPON_FLASHLIGHT" },
                { Name = "Nightstick", Value = "WEAPON_NIGHTSTICK" },
                { Name = "Taser", Value = "WEAPON_STUNGUN" },
                { Name = "Pistol", Value = "WEAPON_COMBATPISTOL" },
            }, index.list, "Scroll to pick a weapon and select to equip it.", {}, true, {
                onListChange = function(Index, Item)
                    index.list = Index;
                    --Visual.Subtitle("onListChange", 100)
                end,
                onSelected = function(Index, Item)
                    Visual.Subtitle("onSelected", 100)
                    print(Item.Value)
                    local ped = GetPlayerPed(PlayerId())
                    GiveWeaponToPed(ped, GetHashKey(Item.Value), 1000, false, true)
                end,
            })

            --

            RageUI.Checkbox('SWAT Gear', description, index.checkbox, {}, {
                onChecked = function()
                    Visual.Subtitle("onChecked", 100)
                    TriggerEvent("SWAT")
                    local ped = GetPlayerPed(PlayerId())
                    GiveWeaponToPed(ped, GetHashKey("WEAPON_SMOKEGRENADE"), 2, false, false)
                    GiveWeaponToPed(ped, GetHashKey("WEAPON_CARBINERIFLE_MK2"), 150, false, true)
                    GiveWeaponComponentToPed(ped, GetHashKey("WEAPON_CARBINERIFLE_MK2"), GetHashKey("COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ"))
                    GiveWeaponComponentToPed(ped, GetHashKey("WEAPON_CARBINERIFLE_MK2"), GetHashKey("COMPONENT_AT_AR_AFGRIP_02"))
                    GiveWeaponComponentToPed(ped, GetHashKey("WEAPON_CARBINERIFLE_MK2"), GetHashKey("COMPONENT_AT_AR_FLSH"))
                    GiveWeaponComponentToPed(ped, GetHashKey("WEAPON_CARBINERIFLE_MK2"), GetHashKey("COMPONENT_AT_SIGHTS"))
                    GiveWeaponComponentToPed(ped, GetHashKey("WEAPON_CARBINERIFLE_MK2"), GetHashKey("COMPONENT_AT_MUZZLE_02"))
                    SetPedArmour(ped, 100)
                end,
                onUnChecked = function()
                    Visual.Subtitle("onUnChecked", 100)
                    TriggerEvent("LSPDUniform")
                end,
                onSelected = function(Index)
                    index.checkbox = Index
                    --- Logic on selected items
                end
            })

            --

            RageUI.Button('Get ammo!', "Description here", { }, true, {onSelected = function() print("HELLO WORLD !") end});


           

        end, function()

            RageUI.Grid(index.grid.default.x, index.grid.default.y, 'Top Text', 'Bottom Text', 'Left Text', 'Right Text', {
                onSelected = function(IndexX, IndexY, X, Y)

                end,
                onPositionChange = function(IndexX, IndexY, X, Y)
                    Visual.Subtitle(string.format('x = %s, y = %s', X, Y), 1000)
                    index.grid.default.x = IndexX
                    index.grid.default.y = IndexY
                end
            }, 1)

            RageUI.GridHorizontal(index.grid.horizontal.x, 'Left Text', 'Right Text', {
                onSelected = function(IndexX, IndexY, X, Y)

                end,
                onPositionChange = function(IndexX, IndexY, X, Y)
                    index.grid.horizontal.x = IndexX
                end
            }, 2)

            RageUI.GridVertical(index.grid.vertical.y, 'Top Text', 'Bottom Text', {
                onSelected = function(IndexX, IndexY, X, Y)

                end,
                onPositionChange = function(IndexX, IndexY, X, Y)
                    index.grid.vertical.y = IndexY
                end
            }, 3)

            RageUI.PercentagePanel(index.percentage, 'Header Text', 'Min Text', 'Max Text', {
                onSelected = function(Percentage)

                end,
                onProgressChange = function(Percentage)
                    index.percentage = Percentage
                end
            }, 4)

            RageUI.ColourPanel("Couleur de Paco", RageUI.PanelColour.HairCut, index.color.primary[1], index.color.primary[2], {
                onColorChange = function(MinimumIndex, CurrentIndex)
                    index.color.primary[1] = MinimumIndex
                    index.color.primary[2] = CurrentIndex
                end
            }, 6, {
                Seperator = { Text = "/" }
            })

            RageUI.ColourPanel("Couleur de paco secondaire", RageUI.PanelColour.HairCut, index.color.secondary[1], index.color.secondary[2], {
                onColorChange = function(MinimumIndex, CurrentIndex)
                    index.color.secondary[1] = MinimumIndex
                    index.color.secondary[2] = CurrentIndex
                end
            }, 6)
        end)

        --> SubMenu : 
        RageUI.IsVisible(subMenu, function()
            --> EXEMPLE ON HOW TO USE HERITAGE WINDOW : 
            RageUI.Window.Heritage(ParentData['mom'], ParentData['dad'])

            --> your logic here ... 
        end, function() end)
    end
end)





RegisterNetEvent('OpenArmoryMenu')
AddEventHandler('OpenArmoryMenu', function()
  Citizen.CreateThread(function()
    RageUI.Visible(armoryMenu, not RageUI.Visible(armoryMenu))
  end)
end)