---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---

print("^1 RageUI - testing file is started. ^0")

local lspdFrontDesk = RageUI.CreateMenu("LSPD", "FRONT DESK")
local subMenu =  RageUI.CreateSubMenu(lspdFrontDesk, "A TITLE", "A SUB TITLE")

function SetPDRank(pdrank)
    pd_rank = pdrank
end 

lspdFrontDesk:DisplayGlare(false)
lspdFrontDesk.Closed = function()
    print('Closed Showcase Menu')
end
lspdFrontDesk.EnableMouse = true
lspdFrontDesk.onIndexChange = function(Index)
    print(Index)
end

--> This will show the glare on the submenu : 
subMenu:DisplayGlare(true)

--> This will show the page counter on the submenu :
subMenu:DisplayPageCounter(true)

local ParentData = {mom = 0, dad = 0}
local index = {
    checkbox = false,
    list = 2,
    heritage = 0.5,
    slider = 50,
    sliderprogress = 50,
    grid = {
        default = { x = 0.5, y = 0.5 },
        horizontal = { x = 0.5 },
        vertical = { y = 0.5 },
    },
    percentage = 0.5,
    color = {
        primary = { 1, 5 },
        secondary = { 1, 5 }
    },
}

local description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur"

Citizen.CreateThread(function()
    while (true) do
        Citizen.Wait(1.0)

        RageUI.IsVisible(lspdFrontDesk, function()

            RageUI.Checkbox('On-duty?', "Check this box to go on-duty as a police officer. You need to be whitelisted!", index.checkbox, {}, {
                onChecked = function()
                    Visual.Subtitle("onChecked", 100)
                    TriggerEvent("LSPDOnDuty")
                end,
                onUnChecked = function()
                    Visual.Subtitle("onUnChecked", 100)
                    TriggerServerEvent("GetLooks")
                end,
                onSelected = function(Index)
                    index.checkbox = Index
                    --- Logic on selected items
                end
            })

        end, function()
        end)
    end
end)

--[[
Keys.Register('E', 'E', 'Open RageUI Showcase menu default.', function()
    RageUI.Visible(lspdFrontDesk, not RageUI.Visible(lspdFrontDesk))
end)]]--

RegisterNetEvent('OpenFrontDeskMenu')
AddEventHandler('OpenFrontDeskMenu', function()
  Citizen.CreateThread(function()
    RageUI.Visible(lspdFrontDesk, not RageUI.Visible(lspdFrontDesk))
  end)
end)